# Launch-level defaults for automode_tb4.launch.py - Flocking Mission
robot_namespace: ""
module_package: "basic_modules"

controller_type: "fsm"

# FSM config - Flocking: repulsion if too close, else attraction, else explore
fsm_config: "--fsm-config --nstates 2 --s0 0 --rwm0 10 --n0 1 --n0x0 0 --c0x0 8 --p0x0 1 --d0x0 0.001 --s1 6 --n1 1 --n1x0 0 --c1x0 7 --t1x0 5 --k1x0 1 "
#fsm_config: "--fsm-config --nstates 1 --s0 0 --rwm0 100 "

# BT config - Flocking: repulsion > attraction > explore
bt_config: "--bt-config --nroot 0 --nchildroot 2 --n0 2 --nchild0 2 --n00 6 --c00 8 --p00 1 --d00 0.001 --n01 5 --a01 6 --n1 5 --a1 0 --rwm1 80 "

ref_model: "ref_model_turtlebot4_gz_nav"

# No working behavior neither fsm nor bt to this point 